    该程序用于检测人体特征，目前有12个属性检测（性别、 衣着、 配饰等）。
用例如下：
$ python3  main.py

输入图片：
![image](https://github.com/sheng-zhong/ml-project/blob/master/image-handel/test_samples/example.png)

输出检测后的图片：
![image](https://github.com/sheng-zhong/ml-project/blob/master/image-handel/detected_frame/detected-example.png)

（图片来源  百度街拍）

配置文件在config.py， 可以通过更改config.py 中的配置检测不同的图片。神经网络结构与在net文件夹下。
